DROP DATABASE IF EXISTS BBDD_CREDENTIALS;
CREATE DATABASE IF NOT EXISTS BBDD_CREDENTIALS;
USE BBDD_CREDENTIALS;

DROP TABLE IF EXISTS CREDENTIALS;
CREATE TABLE CREDENTIALS (

    IdUser INT AUTO_INCREMENT NOT NULL,
    UsrName VARCHAR(30) NOT NULL,
    PwdUser VARCHAR(30) NOT NULL,
    
    PRIMARY KEY (IdUser)
) ENGINE=INNODB;

INSERT INTO CREDENTIALS (UsrName,PwdUser)
VALUES ('evan', 'abc'),
('aman','1234'),
('admin', 'renaido');
select * from CREDENTIALS;