DROP DATABASE IF EXISTS BBDDR_Minecraft;
CREATE DATABASE IF NOT EXISTS BBDDR_Minecraft;
USE BBDDR_Minecraft;

DROP TABLE IF EXISTS ITEMS;
CREATE TABLE ITEMS (

    ItmId INT AUTO_INCREMENT NOT NULL,
    ItmName VARCHAR(30) NOT NULL,
    ItmDesc TEXT NOT NULL,
    ItmStackSize INT NOT NULL,
    ItmImage BLOB
    
    Primary Key
    
) ENGINE=INNODB;

DROP TABLE IF EXISTS BLOCKS;
CREATE TABLE BLOCKS (

	BlkId INT NOT NULL,
    BlkIdName VARCHAR(30) NOT NULL,
    BlkLuminosity INT NOT NULL,
	BlkBlastResistance BOOLEAN NOT NULL,
    BlkFlammable BOOLEAN NOT NULL
    
) ENGINE=INNODB;

DROP TABLE IF EXISTS TOOLS;
CREATE TABLE TOOLS (

	ToolId INT NOT NULL,
    ToolName VARCHAR(30) NOT NULL,
    ToolDurability INT NOT NULL,
    ToolFlammable BOOLEAN NOT NULL,
    ToolDamage FLOAT NOT NULL

) ENGINE=INNODB;

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS (

	BkId INT NOT NULL,
    BkName VARCHAR(30) NOT NULL

) ENGINE=INNODB;

DROP TABLE IF EXISTS POTIONS;
CREATE TABLE POTIONS (

	PotId INT NOT NULL,
    PotName VARCHAR(30) NOT NULL,
    PotEffect TEXT NOT NULL

) ENGINE=INNODB;



